base_de_conocimiento = {
    "angustia": "cuadro de angustia",
    "angustiada": "cuadro de angustia",
    "mucha angustia": "cuadro de angustia",
    "angustiado": "cuadro de angustia",
    "ansioso": "cuadro de ansiedad",
    "soy impulsiva": "cuadro de impulsividad",
    "soy impulsivo": "cuadro de impulsividad",
    "controlar impulsos": "cuadro de impulsividad",
    "soy muy impulsiva": "cuadro de impulsividad",
    "soy muy impulsivo": "cuadro de impulsividad",
    "conductas impulsivas": "cuadro de impulsividad",
    "impulsiva": "cuadro de impulsividad",
    "impulsivo": "cuadro de impulsividad",
    "inestabilidad": "inestabilidad emocional",
    "cambios de animo": "inestabilidad emocional",
    "cambios de anímicos": "inestabilidad emocional",
    "muy inestable": "inestabilidad emocional",
    "cambiante": "inestabilidad emocional",
    "alterada": "inestabilidad emocional",
    "cambios emocionales": "inestabilidad emocional",
    "alterado": "inestabilidad emocional",
    "mucha inseguridad": "inseguridad emocional",
    "insegura": "inseguridad emocional",
    "inseguro": "inseguridad emocional",
    "me cuesta dormir": "insomnio",
    "sin sueño": "insomnio",
    "no puedo dormir": "insomnio",
    "me enojo": "irritabilidad",
    "todo me molesta": "irritabilidad",
    "molesta": "irritabilidad",
    "ganas de vomitar": "nauseas",
    "vomitar": "nauseas",
    "arcada": "nauseas",
    "nervioso": "nerviosismo",
    "nerviosa": "nerviosismo",
    "nervios": "nerviosismo",
    "muy tensionado": "tensión emocional",
    "tensionada": "tensión emocional",
    "tension": "tensión emocional",
    "problemas de memoria": "alteraciones de la memoria",
    "falta memoria": "alteraciones de la memoria",
    "fallas de memoria": "alteraciones de la memoria",
    "amnesia": "alteraciones de la memoria",
    "desmemoriado": "alteraciones de la memoria",
    "lagunas": "alteraciones de la memoria",
    "olvidos": "alteraciones de la memoria",
    "olvido": "alteraciones de la memoria",
    "golpeada": "violencia",
    "violentada": "violencia",
    "agredida": "violencia",
    "abusaron": "violencia",
    "abuso": "violencia",
    "abusada": "violencia",
    "violada": "violencia",
    "violado": "violencia",
    "golpeado": "violencia",
    "lastimado": "violencia",
    "lastimada": "violencia",
    "humillada": "violencia",
    "tristeza": "depresion",
    "compungido": "depresion",
    "cansancio animico": "depresion",
    "estado de agotamiento": "depresion",
    "debil": "depresion",
    "falta de energias": "depresion",
    "fatigada": "depresion",
    "fatiga": "depresion",
    "fatigado": "depresion",
    "autoexigencia": "depresion",
    "autocritica": "depresion",
    "autoreproche": "depresion",
    "muy autocritico": "depresion",
    "baja autoestima": "depresion",
    "inferioridad": "depresion",
    "no valgo": "depresion",
    "me siento menos": "depresion",
    "sin autoestima": "depresion",
    "poco valor": "depresion",
    "valgo poco": "depresion",
    "bajon": "depresion",
    "bajoneado": "depresion",
    "bloqueo": "depresion",
    "bloqueos": "depresion",
    "bloquee": "depresion",
    "deprimo": "depresion",
    "deprimida": "depresion",
    "deprimido": "depresion",
    "derrota": "depresion",
    "derrotada": "depresion",
    "derrotado": "depresion",
    "perdedora": "depresion",
    "vencida": "depresion",
    "abatida": "depresion",
    "desalentado": "depresion",
    "desaliento": "depresion",
    "desconsolado": "depresion",
    "desmotivado": "depresion",
    "desganado": "depresion",
    "sin ganas": "depresion",
    "desanimo": "depresion",
    "poco entusiasmo": "depresion",
    "discute": "depresion",
    "peleo": "depresion",
    "detencion": "depresion",
    "atasco": "depresion",
    "sin fuerzas": "depresion",
    "fracazada": "depresion",
    "bronca": "depresion",
    "lloro": "depresion",
    "abandonada": "depresion",
    "autorreproche": "depresion",
    "susceptible": "depresion",
    "ruborizo": "fobia",
    "temor": "fobia",
    "intolerante": "depresion",
    "divague": "estres",
    "moria": "fobia"
    # Agregué más términos. Puedes seguir expandiendo.
}
